#! python3
#the text in the clipboard shall be copied to shelf file when you add the command py.exe mcb.py save <keyword>
#the text shall be retrieved from shelf file if you add py.exe mcb.py <keyword>
#py.exe mcb.py list loads all the keywords in shelf file
import shelve,pyperclip,sys

mcbshelve = shelve.open('mcb')

if len(sys.argv) == 3:
    if sys.argv[1].lower() == 'save':  
        mcbshelve[sys.argv[2]] = pyperclip.paste()
    elif sys.argv[1].lower() == 'delete' and sys.argv[2] in mcbshelve:
        del mcbshelve[sys.argv[2]]
elif len(sys.argv) == 2:
    if sys.argv[1].lower() == 'list':
        pyperclip.copy(str(list(mcbshelve.keys())))
    elif sys.argv[1] in mcbshelve:
        pyperclip.copy(mcbshelve[sysargv[1]])
    elif sys.argv[1].lower() == 'delete':
        mcbshelve.clear()
        

mcbshelve.close()
